#!/bin/sh

set -e

. "$(dirname $0)/config.sh"
WORKDIR=./work
ORIG_ISO=ubuntu-$VERSION-$DISTRO-$ARCH.iso
COPY_NAME="ubuntu-$VERSION-$DISTRO-$ARCH"
DEST_ISO="$NICKNAME-ubuntu-$VERSION-$DISTRO-$ARCH.iso"
MOUNT="$WORKDIR/mount"

rm -f  $WORKDIR/$ORIG_ISO
rm -f  $WORKDIR/$DEST_ISO
rm -rf $WORKDIR/$COPY_NAME
rmdir $MOUNT
