#!/bin/sh

. "$(dirname $0)/config.sh"


WORKDIR=./work
ORIG_ISO=ubuntu-$VERSION-$DISTRO-$ARCH.iso
COPY_NAME="ubuntu-$VERSION-$DISTRO-$ARCH"
DEST_ISO="$NICKNAME-ubuntu-$VERSION-$DISTRO-$ARCH.iso"
VBOX="VM-$NICKNAME-ubuntu-$VERSION-$DISTRO-$ARCH"

MOUNT="$WORKDIR/mount"

pushd $WORKDIR >/dev/null
  VBoxManage controlvm "$VBOX" poweroff || true
  VBoxManage storagectl "$VBOX" --name SATA --remove
  VBoxManage unregistervm "$VBOX"
  VBoxManage closemedium dvd "./$DEST_ISO"
  VBoxManage closemedium disk "./$VBOX/$VBOX.vmdk"
  rm -rf "$VBOX"
popd >/dev/null



